### ISSUE TITLE
crashes using with geckolib

### ISSUE THREAD

**Issue by PrideVT** [Toma1O6/Guns-RPG#14]
Guns RPG crashes when used with geckolib and works when geckolib is removed.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/2/22 4:13 AM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at software.bernie.geckolib3.util.json.JsonAnimationUtils.getObjectListAsArray(JsonAnimationUtils.java:198) ~[?:3.0.75] {re:classloading}
	at software.bernie.geckolib3.util.json.JsonAnimationUtils.getAnimations(JsonAnimationUtils.java:47) ~[?:3.0.75] {re:classloading}
	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:27) ~[?:3.0.75] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:70) ~[?:3.0.75] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$6377/869058765.apply(Unknown Source) ~[?:?] {}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$null$5(GeckoLibCache.java:88) ~[?:3.0.75] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$6668/1740125095.get(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by Toma1O6** [comment]
At first glance it appears that it's caused by geckolib directly - this mod stores it's animations in animations directory which is used by geckolib too. These incompatible files should be propably ignored by geckolib.
I'll investigate it further today once I get to pc, but this issue may be better suited for geckolib repository.

**Comment by Toma1O6** [comment]
It's caused by geckolib - it expects that all files in `animations` directory are gecko animation files and disregards possibility of other mods using the very same directory for their animations and simply skipping invalid files. Nothing to fix on our side.
